export const PokemonType2 = [
  'poison',
  'water',
  'fire',
  'electric',
  'stile',
  'dark',
  'rock',
  'ice',
  'fighting',
  'dragon',
  'grass',
  'bug',
  'psychic',
  'fairy',
  'ghost',
];

export enum PokemonType {
  'poison' = 'poison',
  'water' = 'water',
  'fire' = 'fire',
  'electric' = 'fire',
  'stile' = 'fire',
  'dark' = 'fire',
  'rock' = 'fire',
  'ice' = 'fire',
  'fighting' = 'fire',
  'dragon' = 'fire',
  'grass' = 'fire',
  'bug' = 'fire',
  'psychic' = 'fire',
  'fairy' = 'fire',
  'ghost' = 'fire',
}
